### ISSUE TITLE
Headphone compatibility 

### ISSUE THREAD

**Issue by 2jz3000** [xyaman/visualyzer#1]
It works flawlessly when music is playing on a device speaker, but crashes when connected to Bluetooth headphones or earphones.

**Comment by xyaman** [comment]
Hi, does this happen with all Bluetooth earphones? Or just AirPods?

Edit: typo

**Comment by xyaman** [comment]
Now it should work, probably tomorrow I will update it in my repo.
Check https://github.com/xyaman/visualyzer/commit/3b06372ad9facad909cb62b96f5f77592fc47a9e
