### ISSUE TITLE
Error loading the preference bundle

### ISSUE THREAD

**Issue by EnzuBR** [xyaman/visualyzer#2]
I am using an iPhone 11 Pro on iOS 13.5, and I got this error

![D5344F67-6D4D-4F3B-ADC5-ECFE85492559](https://user-images.githubusercontent.com/35673495/125946717-1977ff79-0b5f-4059-9578-b67a9f997e8c.png)

**Comment by xyaman** [comment]
Hi, iOS 13 will be supported in the next update!

**Comment by xyaman** [comment]
Now it should work, probably tomorrow I will update it in the repo.
