### ISSUE TITLE
Was showing 1 bar on 0.0.2; now showing nothing on 0.1.0

### ISSUE THREAD

**Issue by kumashi73** [xyaman/visualyzer#4]
I had installed version 0.0.2 but it was only displaying one bar (just using my iPhone speaker). I just upgraded to 0.1.0 and the signal bars disappear entirely, and where the 1 bar was before, now there's nothing. If it helps, I'm using the iPad-style status bar on an iPhone 8. Thanks!

**Comment by xyaman** [comment]
Hi, are you using AirPods? Try increasing sens in preferences.

**Comment by kumashi73** [comment]
Nope, just my iPhone speaker. But I figured it out... the bars actually _were_ working, but they were white visualizer lines on a transparent status bar with a white background! Is there any chance of making the visualizer bars either 1) adaptive in color (as the rest of the status bar icons appear to be) or 2) giving us the option of choosing a color?

**Comment by kumashi73** [comment]
This is working now… disabling and re-enabling the tweak seems to have fixed it. There's still one particular app that's only showing one bar though. I'll open a separate issue for it.
