### ISSUE TITLE
Carrier name still present on lockscreen with toggle enabled

### ISSUE THREAD

**Issue by slimdizzy** [xyaman/visualyzer#5]
Version 0.1.0
iPhone XSMax 14.2
Taurine

The carrier name is still present on the Lock Screen even when the toggle is on in the setting of the tweak. 

STR:
1. Install tweak
2. Set Hide Carrier on in Misc setting area
3. Respring
4. Play audio and lock phone
5.  Use lockscreen with now playing the audio selected prior

Expected result:
Only Visualyzer icon present

Actual result:
Visualyzer and carrier name present on lockscreen

**Comment by xyaman** [comment]
Hi, what's your carrier name?

**Comment by slimdizzy** [comment]
ROGERS

But I also roam so it could also be FREEDOM or BELL.

**Comment by xyaman** [comment]
It seems that first time only works if you play/pause in lockscreen.
I will work on this

**Comment by slimdizzy** [comment]
Yes you are correct. I was able to repro that result as well.

**Comment by xyaman** [comment]
Now it should be fixed https://github.com/xyaman/visualyzer/commit/83c8d66822dc60bc8bba58d07a87b2836849df84.
