### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by greatbritmerica** [xyaman/visualyzer#8]
It just doesn’t show up nothing does

**Comment by xyaman** [comment]
Please add more info, it's imposible to solve a issue with this info.

Add your iOS version, what have you done, visualizer version, etc

**Comment by greatbritmerica** [comment]
I’m on iPhone 11, iOS 13.6, Odyssey jb. I had the tweak downloaded and it worked fine for like two days and now for no reason absolutely nothing displays where the bars should be, when music is playing. It’s just the black background of my status bar that is there. I really don’t know why. I was running latest version, I tried downloading an earlier one but it wouldn’t load in preferences.

**Comment by xyaman** [comment]
Did you try restarting mediaserverd in prefs?

**Comment by greatbritmerica** [comment]
I’ve done that many times actually yes

**Comment by xyaman** [comment]
Did you install another tweak after visualyzer? Are you using airpods?

**Comment by greatbritmerica** [comment]
I have no possible conflicting tweaks, I do have AirPods, I use them on and off, sometimes I just use the device audio or wired earbuds.

**Comment by greatbritmerica** [comment]
I’ve tried uninstalling and reinstalling the tweak, I’ve resprung, rebooted, ldrestarted, uicached, and no matter what it’s just blank when music is playing. No conceivable reason.

**Comment by xyaman** [comment]
Does the time/cellular signal disappears?

**Comment by greatbritmerica** [comment]
time goes away like it’s supposed to, nothing else disappears

**Comment by xyaman** [comment]
Try increasing Airpods Boost in preferences
